"""empty message

Revision ID: 5e5d47657028
Revises: 
Create Date: 2019-07-25 09:40:53.669459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5d47657028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('is_forwarder', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('departure_country', sa.String(length=64), nullable=False),
    sa.Column('departure_port', sa.String(length=64), nullable=False),
    sa.Column('arrival_country', sa.String(length=64), nullable=False),
    sa.Column('arrival_port', sa.String(length=64), nullable=False),
    sa.Column('planned_time', sa.String(length=64), nullable=False),
    sa.Column('estimated_arrival_time', sa.String(length=64), nullable=False),
    sa.Column('estimated_at_real_time', sa.String(length=64), nullable=False),
    sa.Column('consignor', sa.String(length=64), nullable=False),
    sa.Column('consignee', sa.String(length=64), nullable=False),
    sa.Column('cargo', sa.String(length=64), nullable=False),
    sa.Column('cargo_weight', sa.String(length=64), nullable=False),
    sa.Column('total_cargo_weight', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('tr_ex', sa.String(length=64), nullable=False),
    sa.Column('custom_reference', sa.String(length=64), nullable=False),
    sa.Column('container_nr', sa.String(length=64), nullable=True),
    sa.Column('container_type', sa.String(length=64), nullable=True),
    sa.Column('car_type', sa.String(length=64), nullable=False),
    sa.Column('car_model', sa.String(length=64), nullable=False),
    sa.Column('number_plate', sa.String(length=64), nullable=False),
    sa.Column('trailer_plate', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
